source "https://rubygems.org"

ruby "2.4.0"

gem "bootsnap", ">= 1.1.0", require: false
gem "coffee-rails", "~> 4.2"
gem "jbuilder", "~> 2.5"
gem "nokogiri"
gem "oj"
gem "pg"
gem "puma", "~> 3.11"
gem "rails", "~> 5.2.0"
gem "sass-rails", "~> 5.0"
gem "turbolinks", "~> 5"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "uglifier", ">= 1.3.0"

group :development, :test do
  gem "pry-rails"
  gem "rspec-rails", "~> 3.8"
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "web-console", ">= 3.3.0"
end

group :test do
  gem "chromedriver-helper"
  gem "capybara", ">= 2.15", "< 4.0"
  gem "database_cleaner"
  gem "factory_bot_rails"
  gem "fuubar"
  gem "shoulda-matchers", git: "git@github.com:thoughtbot/shoulda-matchers.git"
  gem "selenium-webdriver"
  gem "vcr"
  gem "webmock"
end
